# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
url: https://blog.yutao.co
baseurl: /
title: 王宇涛的博客
description: >
    Yutao's Site | 王宇涛的小站


## => Language and Timezone
##############################
lang: zh
timezone: Asia/Shanghai


## => Author and Social
##############################
author:
  name: 王宇涛
  url: https://yutao.co/
  bio: i'm a handsome guy.
  email: wyt1271030564@gmail.com
  github:  yutao517
  twitter: wyt517
  weibo: 6310353962
  csdn: https://blog.csdn.net/weixin_46415378/

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: yutao517/yutao517.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /
  home: /blog
  archive: /blog/archive.html
  rss:  /feed.xml




## => Paginate
##############################
paginate: 7
paginate_path: /blog/page:num




## => Pageview
##############################
pageview:
  provider: leancloud
  leancloud:
    app_id: uAG3OhdcH8H4fxSqXLyBljA7-gzGzoHsz
    app_key: Mzf5m9skSwYVWVXhGiYMNyXs
    app_class: ThomasBlog


## => Analytics
##############################
analytics:
  provider: google
  google:
    tracking_id: UA-71907556-1


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - README-*.md
  - README.md
  - gulpfile.js
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


## => Server
##############################
server_url: "0.0.0.0"
port: 4001
